version: "3.3"
services:
  backend:
    restart: always
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend:latest
    container_name: sausage-backend
    networks:
      sausage_network:
        ipv4_address: 172.20.0.6
    env_file: 
      - .env
    environment:
      REPORT_PATH: /log/reports
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      spring.cloud.vault.enabled: "false"
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: sausage-store
  backend-report:
    restart: always
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    env_file: 
      - .env
    environment:
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      spring.cloud.vault.enabled: "false"
      PORT: 8081
    networks:
      sausage_network:
        ipv4_address: 172.20.0.8
     
  frontend:
    restart: always
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    environment:
      DEFAULT_HOST: sausage-store
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
#    ports:
#      - "8080:80"
#      - "8443:443"
    networks:
      sausage_network:
        ipv4_address: 172.20.0.4
networks:
  sausage_network: 
    driver: bridge

