version: "3.3"
services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend:latest
    container_name: sausage-backend
    environment:
      spring.cloud.vault.enabled: "false"
      SPRING_DATASOURCE_USERNAME: std-015-31
      SPRING_DATASOURCE_PASSWORD: Testusr1234
      SPRING_DATASOURCE_URL: jdbc:postgresql://rc1b-x9g34dxygn60eu1y.mdb.yandexcloud.net:6432/std-015-31
 #     SPRING_DATA_MONGODB_URI: mongodb://std-015-31:Testusr1234@rc1c-wqwzfolame1vyonu.mdb.yandexcloud.net:27018/std-015-31?tls=true
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    networks:
      - sausage_network
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    environment:
      spring.cloud.vault.enabled: "false"
      DB: mongodb://std-015-31:Testusr1234@rc1c-wqwzfolame1vyonu.mdb.yandexcloud.net:27018/std-015-31?tls=true
    ports:
      - "8080:8080"
    networks:
      - sausage_network
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    ports:
      - "80:80"
    networks:
      - sausage_network
networks:
  sausage_network: 
    driver: bridge

