version: "3.3"
services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend:latest
    container_name: sausage-backend
    environment:
      spring.cloud.vault.enabled: "false"
      SPRING_DATASOURCE_USERNAME: $(vault kv get -field=spring.datasource.username secret/sausage-store)
      SPRING_DATASOURCE_PASSWORD: $(vault kv get -field=spring.datasource.password secret/sausage-store)
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
 #     SPRING_DATA_MONGODB_URI: mongodb://std-015-31:Testusr1234@rc1c-wqwzfolame1vyonu.mdb.yandexcloud.net:27018/std-015-31?tls=true
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    networks:
      - sausage_network
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    environment:
      spring.cloud.vault.enabled: "false"
      DB: $(vault kv get -field=spring.datasource.mongo secret/sausage-store)
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - sausage_network
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    ports:
      - "80:80"
    networks:
      - sausage_network
networks:
  sausage_network: 
    driver: bridge

