version: "3.3"
services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend:latest
    container_name: sausage-backend
    networks:
      - sausage_network
    env_file: 
      - .env
    environment:
      spring.cloud.vault.enabled: "false"
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true" 
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    env_file: 
      - .env
    environment:
      spring.cloud.vault.enabled: "false"
      PORT: 8081
    networks:
      - sausage_network
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    ports:
      - "80:80"
    networks:
      - sausage_network
networks:
  sausage_network: 
    driver: bridge

