version: "3.4"
services:
  backend-blue:
    restart: always
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
#    healthcheck:
#      test: curl --fail -s http://localhost:8080/actuator/health
#      interval: 30s
#      timeout: 10s
#      start_period: 20s
#      retries: 6
    container_name: backend-blue
    networks:
      sausage_network:
        ipv4_address: 172.20.0.6
    env_file: 
      - .env
    environment:
      REPORT_PATH: /log/reports
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      spring.cloud.vault.enabled: "false"
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: sausage-store

  backend-blue-proverka:
    restart: always
    image: health:latest
    healthcheck:
      test: curl --fail -s http://172.20.0.6:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
    container_name: backend-blue-proverka
    networks:
      sausage_network:
        ipv4_address: 172.20.0.11

  backend-green:
    restart: always
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend:latest
    ports:
      - "8082:8080"
    expose:
      - "8082"
#    healthcheck:
#      test: curl --fail -s http://localhost:8082/actuator/health
#      interval: 30s
#      timeout: 10s
#      start_period: 20s
#      retries: 6
    container_name: backend-green
    networks:
      sausage_network:
        ipv4_address: 172.20.0.9
    env_file: 
      - .env
    environment:
      REPORT_PATH: /log/reports
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      spring.cloud.vault.enabled: "false"
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: sausage-store   

backend-green-proverka:
    restart: always
    image: health:latest
    ports:
      - "8082:8080"
    expose:
      - "8082"
    healthcheck:
      test: curl --fail -s http://172.20.0.9:8082/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
    container_name: backend-green-proverka
    networks:
      sausage_network:
        ipv4_address: 172.20.0.13



  backend-report:
    restart: always
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    env_file: 
      - .env
    environment:
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      spring.cloud.vault.enabled: "false"
      PORT: 8081
    networks:
      sausage_network:
        ipv4_address: 172.20.0.8
     
  frontend:
    restart: always
    image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    environment:
      DEFAULT_HOST: sausage-store
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
#    ports:
#      - "8080:80"
#      - "8443:443"
    networks:
      sausage_network:
        ipv4_address: 172.20.0.4
networks:
  sausage_network: 
    driver: bridge

