stages:
  - release
  - deploy

variables:
  VERSION: 0.1.${CI_PIPELINE_ID}

upload-helm:
  stage: release
  image: lwolf/helm-kubectl-docker:v1.21.1-v3.6.0
  when: manual
  environment:
    name: dev-helm
    url: https://nexus.k8s.praktikum-services.tech/repository/sausage-store-helm-anar-amrakhov-15/sausage-store-${VERSION}.tgz
  before_script:
    - mkdir -p ~/.kube
    - echo -n $KUBE_CONFIG | base64 -d > ~/.kube/config
    - apk --no-cache add curl
  script:
    - cd sausage-store-chart
    - helm package --version $VERSION ./    
    - curl -u "${NEXUS_REPO_USER}:$(echo $NEXUS_REPO_PASS | base64 -d)" ${NEXUS_HELM_REPO} --upload-file sausage-store-${VERSION}.tgz

  after_script:
    - rm ~/.kube/config

deploy-helm:
  stage: deploy
  image: lwolf/helm-kubectl-docker:v1.21.1-v3.6.0
  when: manual
  environment:
    name: dev-helm
    url: https://15-anar-amrakhov.k8s.praktikum-services.tech
  before_script:
    - mkdir -p ~/.kube
    - echo -n $KUBE_CONFIG | base64 -d > ~/.kube/config
  script:
    - helm repo add nexus $NEXUS_HELM_REPO --username ${NEXUS_REPO_USER} --password $(echo $NEXUS_REPO_PASS | base64 -d)
    - helm repo update
    - >
      helm upgrade --install sausage-store \
        --set environment=test \
        --set backend.secrets.postgresHost=${SPRING_DATASOURCE_URL}\
        --set backend.secrets.postgresUser=${SPRING_DATASOURCE_USERNAME} \
        --set backend.secrets.postgresPassword=${SPRING_DATASOURCE_PASSWORD}\
        --set backend.secrets.mongoHost=${SPRING_DATA_MONGODB_URI}\
        --set backend.secrets.mongoDB=${SPRING_DATA_MONGODB_URI}\
        --set backend-report.secrets.postgresHost=${SPRING_DATASOURCE_URL}\
        --set backend-report.secrets.postgresUser=${SPRING_DATASOURCE_USERNAME}\
        --set backend-report.secrets.postgresPassword=${SPRING_DATASOURCE_PASSWORD}\
        --set backend-report.secrets.mongoHost=${SPRING_DATA_MONGODB_URI}\
        --set backend-report.secrets.mongoDB=${SPRING_DATA_MONGODB_URI}\
        --set secrets.dockerConfigJson=${DOCKER_CONFIG_JSON} \
        --atomic --timeout 15m \
          nexus/sausage-store
  after_script:
    - rm ~/.kube/config
