secrets:
  postgresHost: "amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi14OWczNGR4eWduNjBldTF5Lm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDE1LTMx"
  postgresUser: "c3RkLTAxNS0zMQ=="
  postgresPassword: "VGVzdHVzcjEyMzQ="
  mongoHost: "bW9uZ29kYjovL3N0ZC0wMTUtMzE6VGVzdHVzcjEyMzRAcmMxYy13cXd6Zm9sYW1lMXZ5b251Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAxNS0zMT90bHM9dHJ1ZQ=="
  mongoDB: "bW9uZ29kYjovL3N0ZC0wMTUtMzE6VGVzdHVzcjEyMzRAcmMxYy13cXd6Zm9sYW1lMXZ5b251Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAxNS0zMT90bHM9dHJ1ZQ=="
