---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-frontend:latest
      name: frontend
      imagePullPolicy: IfNotPresent
      ports:
        - name: frontend
          containerPort: 80
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/
  volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf    
  # чтобы Кубер мог скачивать образы из нашего GitLab Registry  
  imagePullSecrets:
    - name: docker-config-secret
