apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - image: {{ .Values.global.imageRegistry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          name: {{ .Values.name }}
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-helm
                  key: postgres_host
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-helm
                  key: postgres_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-helm
                  key: postgres_password
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-helm
                  key: mongo_host
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: postgres-helm
                  key: mongo_db
            - name: SPRING_FLYWAY_BASELINE-ON-MIGRATE
              value: "{{ .Values.global.springFlywayBaseline }}"
            - name: REPORT_PATH
              value: "{{ .Values.global.reportPath }}"
            - name: spring.cloud.vault.enabled
              value: "{{ .Values.global.springCloudVaultEnabled }}"
            - name: SPRING_FLYWAY_ENABLED
              value: "{{ .Values.global.springFlywayEnables }}"
          ports:
            - name: backend
              containerPort: {{ .Values.global.backendPort | int }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.global.backendPort | int }}
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret-helm
