---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-helm
data:
  postgres_host: {{ .Values.secrets.postgresHost | b64enc }}
  postgres_user: {{ .Values.secrets.postgresUser | b64enc }}
  postgres_password: {{ .Values.secrets.postgresPassword | b64enc }}
  mongo_host: {{ .Values.secrets.mongoHost | b64enc }}
  mongo_db: {{ .Values.secrets.mongoDB | b64enc }}
type: Opaque