stages:
  - deploy
deploy:
  stage: deploy
  image: bitnami/kubectl:1.24.3
  when: manual
  environment:
    name: dev
    url: https://15-anar-amrakhov.k8s.praktikum-services.tech
  before_script: 
    - mkdir ~/.kube
    - echo -n $KUBE_CONFIG | base64 -d > ~/.kube/config
  script:
    - cd kubernetes
    - kubectl apply -f frontend/configmap.yaml
    - kubectl apply -f frontend/ --recursive
    - kubectl apply -f backend/ --recursive
    - kubectl apply -f backend-report/ --recursive
  after_script:
    - rm ~/.kube/config
