---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret-helm
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.secrets.dockerConfigJson }}
type: kubernetes.io/dockerconfigjson
