---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - image: gitlab.praktikum-services.ru:5050/std-015-31/sausage-store/sausage-backend-report:latest
          name: backend-report
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: PORT
              value:  "8080"
            - name: REPORT_PATH 
              value: /log/reports
            - name: spring.cloud.vault.enabled
              value: "false"
            - name: SPRING_FLYWAY_BASELINE-ON-MIGRATE
              value: "true"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://rc1b-x9g34dxygn60eu1y.mdb.yandexcloud.net:6432/std-015-31
            - name: SPRING_DATASOURCE_USERNAME
              value: std-015-31
            - name: SPRING_DATASOURCE_PASSWORD
              value: Testusr1234
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://std-015-31:Testusr1234@rc1c-wqwzfolame1vyonu.mdb.yandexcloud.net:27018/std-015-31?tls=true
            - name: DB
              value: mongodb://std-015-31:Testusr1234@rc1c-wqwzfolame1vyonu.mdb.yandexcloud.net:27018/std-015-31?tls=true
          ports:
            - name: backend-report
              containerPort: 8080
          livenessProbe:
        # проверка живучести выполнит запрос HTTP GET       
            httpGet:
          # путь к запросу в HTTP-запросе          
              path: /actuator/health
          # порт, к которому должна подключиться проверка        
              port: 8080
        # перед исполнением первой проверки подождать 15 секунд, пока стартанёт бэкенд          
            initialDelaySeconds: 15
        # период выполнения проверки
            periodSeconds: 30
        # максимальное время выполнения проверки (по умолчанию 1 раз)
            timeoutSeconds: 2
        # сколько раз пробовать попытку, если она провалилась (по умолчанию 1 раз)
            failureThreshold: 6
  # чтобы Кубер мог скачивать образы из нашего GitLab Registry  
      imagePullSecrets:
        - name: docker-config-secret
